Added a new optional flag (-c) for the instance if you wanted the nam…
Unidata/nexus-tools pull request #3
Opened 2021-08-17 17:06 UTC by tiffanycmeyer13

…e of the file on the nexus server to be different than the filename you were uploading

2021-08-17 17:07 UTC, tiffanycmeyer13 commented
Sean, you can decide if you want to incorporate this or add any further checks, but I thought I'd at least give you the option if you want to merge it in

2021-08-17 18:57 UTC, lesserwhirls commented
The only that that jumps out to me is that we'd want to check that the array of filenames (`EXPRESSION`) is not greater than 1 when the new `-c` flag is used, since that combo does not make sense.

2021-08-18 16:09 UTC, tiffanycmeyer13 commented
Not sure what exit status I should put (not super familiar with bash...)

2021-08-18 23:23 UTC, lesserwhirls requested changes

2021-08-18 23:23 UTC, lesserwhirls commented on bash/nexus-upload.sh
> +  exit "Cannot use the change filename (-c flag) with multiple file uploads"
Would you mind changing this to:

~~~bash
    echo "Cannot use the change filename (-c flag) with multiple file uploads"
    exit 1
~~~

2021-08-18 23:23 UTC, lesserwhirls commented on bash/nexus-upload.sh
> +  -c: change the filename on the server side
Might be worth adding `(incompatible when uploading multiple files)`

2021-08-19 21:44 UTC, lesserwhirls commented
Awesome = thanks @tiffanycmeyer13!

2021-08-19 21:46 UTC, lesserwhirls commented
Holding off on merging for now as we will pair up tomorrow to rebase and clean up the history.

2021-08-20 18:20 UTC, lesserwhirls approved these changes

2021-08-20 18:20 UTC, merged